Name: Recipe
Type: FolderType
Children:
- Name: Recipes
  Id: g=174c894e45231554e6ae6af58c1922df
  Supertype: MainBodyTemplate
  ReferenceType: HasComponent
  Children:
  - Name: NavigationPanel1
    Type: NavigationPanel
    Children:
    - Name: Panels
      Type: BaseObjectType
      Children:
      - Name: Panel1
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":-1,"LocaleId":"","Text":""}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: {"IdType":2,"Id":"4f7847777b73cab78ca16b43c1cc76cb","Namespace":30}
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":5}
      - Name: Panel2
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":-1,"LocaleId":"","Text":""}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: {"IdType":2,"Id":"801832eb86f340ad48ffdee84b927641","Namespace":30}
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":5}
    - Name: CurrentPanel
      Type: NodePointer
      DataType: NodeId
      AccessLevel: Read
      Value: {"IdType":0,"Id":0,"Namespace":-1}
      Children:
      - Name: Kind
        Type: PropertyType
        DataType: NodeId
        Value: {"Id":6,"Namespace":5}
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 300.0
    - Name: Height
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 300.0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 3
    - Name: VerticalAlignment
      Type: BaseVariableType
      DataType: VerticalAlignment
      ModellingRule: Optional
      Value: 3
    - Name: TabPosition
      Type: BaseVariableType
      DataType: NavigationPanelTabPositionEnum
      ModellingRule: Optional
      Value: 1
- Name: RecipeMachineSetup
  Id: g=801832eb86f340ad48ffdee84b927641
  Supertype: MainBodyTemplate
  ReferenceType: HasComponent
  Children:
  - Name: Label1
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"LocaleId":"en-US","Text":"Label2"}
- Name: RecipeProcess
  Id: g=4f7847777b73cab78ca16b43c1cc76cb
  Supertype: MainBodyTemplate
  ReferenceType: HasComponent
  Children:
  - Name: Label1
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      ModellingRule: Optional
      Value: {"LocaleId":"en-US","Text":"Label1"}
